#logging.file=F:/log/sell.log
#logging.path=F:/log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: 123456
    url: jdbc:mysql://39.105.115.22:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
#  context-path: /sell
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxc88f38cab217c2bb
  mpAppSecret: 1eeccff772b2df152ddae9fb416087e2
