#logging.file=F:/log/sell.log
#logging.path=F:/log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: 123456
    url: jdbc:mysql://39.105.115.22:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379

server:
#  context-path: /sell
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxc88f38cab217c2bb
  mpAppSecret: 1eeccff772b2df152ddae9fb416087e2
  openAppId:
  openAppSecret:
  mchId: mchIdTest
  mchKey: mchKeyTest
  keyPath: keyPathTest需要下载商家证书
  notifyUrl: http://ludan.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: IbrUl5sdszksVBXqUYJ0lnIjspeikckiErRqEYf0dzo

projectUrl:
  wechatMpAuthorize: http://ludan.natapp1.cc
  wechatOpenAuthorize: http://ludan.natapp1.cc
  sell: http://ludan.natapp1.cc

#设置日志等级mapper
logging:
  level:
    com.imooc.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml


password:
  salt: geelysdafaqj23ou 89ZXcj@#$@#$#@KJdjklj;D../dSF.,
ftp:
  user: ftpuser
  pass: 123456
#  server:
  ip: 39.105.115.22
  port: 21
  remotePath: img
  httpPrefix: http://img.marinatedegg.top:81/

